version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  request-manager:
    build:
      context: ./
      dockerfile: request-manager/Dockerfile
    ports:
      - "127.0.0.1:32308:32308"
    depends_on:
      - mysql
    environment:
      INIT_SPINCYCLE_DB: "yes"
      SPINCYCLE_MYSQL_DSN: "root:@tcp(mysql:3306)/spincycle_development"
      SPINCYCLE_JRCLIENT_URL: "http://job-runner:32307"
  job-runner:
    build:
      context: ./
      dockerfile: job-runner/Dockerfile
    depends_on:
      - mysql
    environment:
      SPINCYCLE_RMCLIENT_URL: "http://request-manager:32308"
