version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - "3306"
  request-manager:
    build:
      context: ./
      dockerfile: request-manager/Dockerfile
    ports:
      - "32308:32308"
    depends_on:
      - mysql
    environment:
      INIT_SPINCYCLE_DB: "yes"
      SPINCYCLE_SERVER_ADDR: "request-manager:32308"
      SPINCYCLE_MYSQL_DSN: "root:@tcp(mysql:3306)/spincycle_development"
      SPINCYCLE_JR_CLIENT_URL: "http://job-runner:32307"
  job-runner:
    build:
      context: ./
      dockerfile: job-runner/Dockerfile
    depends_on:
      - mysql
    environment:
      SPINCYCLE_SERVER_ADDR: "job-runner:32307"
      SPINCYCLE_RM_CLIENT_URL: "http://request-manager:32308"
    expose:
      - "32307"
