[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "github.com/alicebob/miniredis"
  version = "2.1.0"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "2.0.2"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
