[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "~1.0"

[[constraint]]
  name = "github.com/alicebob/miniredis"
  version = "~2.1"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "~2.0"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "~1.0"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "~3.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "b2ce2384e17bbe0c6d34077efa39dbab3e09123b"

[prune]
  go-tests = true
  unused-packages = true
