title: Spin Cycle
description: >-
  Platform automation at scale
url: https://square.github.io/spincycle
twitter_username: square
github_username: square
markdown: kramdown
plugins:
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

theme: jekyll-theme-slate
